DECLARE @CODPERIODO CHAR(9)
SELECT @CODPERIODO = '202020213'

IF( CAST(SUBSTRING(@CODPERIODO,1,4) AS INT) = (CAST(SUBSTRING(@CODPERIODO,5,4) AS INT)-1) AND SUBSTRING(@CODPERIODO,9,1) LIKE '[1-3]' )
	SELECT 'CUMPLE'




